### PR TITLE
fix: make wssBroadcast an async function

### LINKED ISSUE #1686: chromium extension-runner reloadAllExtensions should wait wssBroadcast to be processed by the connected clients
As a followup to #1392, the `chromium` extension-runner should wait the `"webExtReloadAllExtensions"` message (broadcasted from the websocket server part of the `chromium` extension runner) to have been received and handled by all the connected clients [1] (See https://github.com/mozilla/web-ext/pull/1392/files#r231533242).

[1]:where the connected client is the "extension manager extension" used to remotely control a chromium instance, in particular to reload the extension passed to the `web-ext run` command automatically when one of its file has been changed).

### PR DESCRIPTION
**Pull request by ccarruitero**
fixes #1686

### CODE REVIEW

**Comment by ccarruitero** [comment]
@Rob--W thanks for the explanation. I'll work on complete the fix

**Comment by ccarruitero** [comment]
@Rob--W I added the changes you mentioned, but I have some doubts about tests.

First, I planned to test that the event listener was added, I found how to get the number of events listeners, but not sure why is failing

Then I think to test that the method wait for the message back for return, but really not sure how to test this. 

Do you have any thought?

File: src/extension-runners/chromium.js [hunk 1]
```diff
@@ -217,7 +231,8 @@ export class ChromiumExtensionRunner {
         if (msg.type === 'webExtReloadAllExtensions') {
           const devExtensions = await getAllDevExtensions();
           for (var ext of devExtensions) {
-            reloadExtension(ext.id);
+            await reloadExtension(ext.id);
+            ws.send(JSON.stringify({ type: 'webExtReloadExtensionComplete' }));
```
Comment (Rob--W) [inline src/extension-runners/chromium.js]: This should be done after the loop.

And although it does currently not matter, I hope that you are aware of the fact that previously the `reloadExtension` was run in parallel, but after the change they are run sequentially. In general, if you want to keep running them in parallel, use use an `Array`'s `map` method to generate an array of promises, and then use `Promise.all`.

File: src/extension-runners/chromium.js [hunk 2]
```diff
@@ -151,12 +151,26 @@ export class ChromiumExtensionRunner {
...
   }
 
-  wssBroadcast(data: Object) {
+  async wssBroadcast(data: Object) {
+    const promisesArray = [];
     for (const client of this.wss.clients) {
       if (client.readyState === WebSocket.OPEN) {
-        client.send(JSON.stringify(data));
+        promisesArray.push(new Promise((resolve) => {
+          client.on('message', async (message) => {
```
Comment (Rob--W) [inline src/extension-runners/chromium.js]: With this implementation, the number of `message` listeners will increase whenever reload is called.

I suggest to store the list of clients in an array, create one function, and then use that function as a listener for every `client`. When any of the clients return a message, all listeners should be unregistered, and the promise should be resolved. When a client is disconnected, the listener should be unregistered and the client be removed from the list (and if the list is empty, the promise should be resolved).

File: src/extension-runners/chromium.js [hunk 3]
```diff
@@ -151,12 +151,37 @@ export class ChromiumExtensionRunner {
...
+          resolve();
+        }
+      };
+
+      clients.forEach((client) => {
+        if (client.readyState === WebSocket.OPEN) {
+          client.on('message', webExtReloadComplete);
+          client.on('close', () => {
+            client.removeListener('message', webExtReloadComplete);
+            clients.splice(clients.indexOf(client), 1);
```
Comment (Rob--W) [inline src/extension-runners/chromium.js]: Let's use a `Set` instead of an `Array`, then you can use `clients.delete(client)` instead of having to use `splice` / `indexOf`.

Whenever you remove an element from the set, also check whether it may be necessary to check whether the set is empty, i.e. `if (clients.size === 0) { resolve(); }`.

File: src/extension-runners/chromium.js [hunk 4]
```diff
@@ -151,12 +151,37 @@ export class ChromiumExtensionRunner {
...
+            client.removeListener('message', webExtReloadComplete)
+          );
+          resolve();
+        }
+      };
+
+      clients.forEach((client) => {
+        if (client.readyState === WebSocket.OPEN) {
+          client.on('message', webExtReloadComplete);
+          client.on('close', () => {
```
Comment (Rob--W) [inline src/extension-runners/chromium.js]: The close listeners should also be removed eventually.

File: src/extension-runners/chromium.js [hunk 5]
```diff
@@ -151,12 +151,37 @@ export class ChromiumExtensionRunner {
...
+      if (!clients || clients.length === 0) {
+        resolve();
       }
-    }
+
+      const webExtReloadComplete = async (message) => {
+        const msg = JSON.parse(message);
+
+        if (msg.type === 'webExtReloadExtensionComplete') {
+          clients.forEach((client) =>
```
Comment (Rob--W) [inline src/extension-runners/chromium.js]: `for (let client of clients) {`

File: src/extension-runners/chromium.js [hunk 6]
```diff
@@ -151,12 +151,37 @@ export class ChromiumExtensionRunner {
...
+            client.removeListener('message', webExtReloadComplete)
```
Comment (Rob--W) [inline src/extension-runners/chromium.js]: Let's be consistent - use `off` because you used `on` before.

(the behavior is identical, but for consistency use on/off (preferred) or addListener/removeListener).

File: src/extension-runners/chromium.js [hunk 7]
```diff
@@ -217,8 +242,10 @@ export class ChromiumExtensionRunner {
         if (msg.type === 'webExtReloadAllExtensions') {
           const devExtensions = await getAllDevExtensions();
           for (var ext of devExtensions) {
+            // just removing await .. fix and keep feature?
```
Comment (Rob--W) [inline src/extension-runners/chromium.js]: The `await` is necessary. Otherwise there is no guarantee that all extensions have been reloaded.

Assuming that `reloadExtension` never rejects, the logic would be

```
await Promise.all(devExtensions.map(ext => reloadExtension(ext.id)));
```

File: tests/unit/test-extension-runners/test.chromium.js [hunk 8]
```diff
@@ -357,4 +368,58 @@ describe('util/extension-runners/chromium', async () => {
...
+      });
+      assert(await runnerInstance.reloadAllExtensions());
+    });
+
+    it('resolve when all client disconnect', async (done) => {
+      await connectClient();
+      await wsClient.close();
+
+      try {
+        await runnerInstance.reloadAllExtensions().catch(e => {
```
[the remark this answers is not in the document]
Comment (Rob--W) [reply tests/unit/test-extension-runners/test.chromium.js]: To know when a client has closed, tou need to await its "close".

File: tests/unit/test-extension-runners/test.chromium.js [hunk 9]
```diff
@@ -357,4 +368,58 @@ describe('util/extension-runners/chromium', async () => {
...
+
+    afterEach(async () => {
+      wsClient.close();
+      await runnerInstance.exit();
+    });
+
+    it('does not resolve before complete message from client', async () => {
+      await connectClient();
+      await runnerInstance.reloadAllExtensions();
+      assert.fail();
```
[the remark this answers is not in the document]
Comment (Rob--W) [reply tests/unit/test-extension-runners/test.chromium.js]: First, to comment on your code snippet:
Never use 

```
try {
  await somePromise.catch(handleError);
} catch (e) {
  handleError(e);
}
```

... because the first `.catch` will ensure that the promise never rejects.

Instead, do

```
try {
  await somePromise;
} catch (e) {
  handleError(e);
}
```

And if you are expecting a test, then you shouldn't use the above pattern. Because if `somePromise` were to resolve successfully, then `handleError` is not called. The code should cause a test failure if the error is not thrown, and otherwise (if an error is thrown), check the error and proceed to the next part of the test.

Secondly, it seems that you are attempting to await a promise, and you want to verify that it doesn't resolve until an explicit message has been sent. That logic is flawed, because the test would then wait forever.
Instead of waiting forever, what you should do is to have the following logic:

1. Initialize flag, e.g. to false.
2. create client and register message listener on client.
3. await `reloadAllExtensions()`.
4. Set flag to true.

The message listener should then wait a little bit (e.g. 333ms), assert that the flag is still false (i.e. that `reloadAllExtensions` has not returned yet), and then return a message.

**Comment by ccarruitero** [comment]
@Rob--W I just updated the PR. Sorry for delay.

Take a look when you have a chance.

File: tests/unit/test-extension-runners/test.chromium.js [hunk 10]
```diff
@@ -357,4 +368,71 @@ describe('util/extension-runners/chromium', async () => {
...
+      wsClient = new WebSocket(wsURL);
+      await new Promise((resolve) => wsClient.on('open', resolve));
+    };
+
+    afterEach(async () => {
+      wsClient.close();
+      await runnerInstance.exit();
+    });
+
+    it('does not resolve before complete message from client', async (done) => {
```
Comment (ccarruitero) [inline tests/unit/test-extension-runners/test.chromium.js]: I modified the test based on https://github.com/mozilla/web-ext/pull/1695#discussion_r324148564, but couldn't make this pass yet.

I'm setting a variable (`reloadMessage`), creating a client and registering a message listener inside a promise (`waitCompleteMessage`), that change the variable value and resolve when receive complete message. Add a timeout and await `reloadAllExtensions`.

The timeout is asserting that variable isn't change, send complete message, await `waitCompleteMessage` and assert variable was changed.

But `waitCompleteMessage` isn't resolving. I was adding some logs and notice that the listener doesn't called after sent complete message, even when is added before `reloadAllExtensions`.

Do you have any advice?

File: tests/unit/test-extension-runners/test.chromium.js [hunk 11]
```diff
@@ -357,4 +368,71 @@ describe('util/extension-runners/chromium', async () => {
...
+        const msg = JSON.stringify({type: 'webExtReloadExtensionComplete'});
+        wsClient.send(msg);
+      });
+      assert.isOk(await runnerInstance.reloadAllExtensions());
+    });
+
+    it('resolve when all client disconnect', async () => {
+      await connectClient();
+      wsClient.on('close', async () => {
+        assert.isOk(await runnerInstance.reloadAllExtensions());
```
Comment (Rob--W) [inline tests/unit/test-extension-runners/test.chromium.js]: This implementation is incorrect. The test will finish as soon as `wsClient.close();` has been called. You should call `reloadAllExtensions()`, save its return value in a variable, call `wsClient.close()` and then wait for the resolution of the promise that you've saved in the variable.

File: tests/unit/test-extension-runners/test.chromium.js (hunk 10 above)
Comment (ccarruitero) [reply tests/unit/test-extension-runners/test.chromium.js]: I finally fix this test. I'm using just one flag that check is false before and become true after `reloadAllExtensions`, but let me know if you prefer to use two flags instead.

File: src/extension-runners/chromium.js [hunk 12]
```diff
@@ -151,12 +151,37 @@ export class ChromiumExtensionRunner {
...
+            client.removeListener('message', webExtReloadComplete);
+          }
+          resolve();
+        }
+      };
+
+      for (const client of clients) {
+        if (client.readyState === WebSocket.OPEN) {
+          client.on('message', webExtReloadComplete);
+          client.on('close', () => {
```
Comment (Rob--W) [inline src/extension-runners/chromium.js]: The `close` listeners are still here. They need to be removed eventually, just like the `'message'` listener.

File: src/extension-runners/chromium.js [hunk 13]
```diff
@@ -151,12 +151,37 @@ export class ChromiumExtensionRunner {
...
+            client.off('message', webExtReloadComplete);
+            clients.delete(client);
+          });
+
+          client.send(JSON.stringify(data));
+        }
```
Comment (Rob--W) [inline src/extension-runners/chromium.js]: Add an `else` block that calls `clients.delete(client);`, and move the `if (clients.size === 0) {` check from above to after the loop.

**Comment by ccarruitero** [comment]
@Rob--W thanks for all your comments, I just updated the PR. Take a look when you have a chance

File: tests/unit/test-extension-runners/test.chromium.js [hunk 14]
```diff
@@ -357,4 +368,75 @@ describe('util/extension-runners/chromium', async () => {
...
+    const connectClient = async () => {
+      const wssInfo = runnerInstance.wss.address();
+      const wsURL = `ws://${wssInfo.address}:${wssInfo.port}`;
+      wsClient = new WebSocket(wsURL);
+      await new Promise((resolve) => wsClient.on('open', resolve));
+    };
+
+    afterEach(async () => {
+      if (wsClient) {
+        wsClient.close();
```
[the remark this answers is not in the document]
Comment (Rob--W) [reply tests/unit/test-extension-runners/test.chromium.js]: ^ `wsClient = null;` is still missing.

File: tests/unit/test-extension-runners/test.chromium.js [hunk 15]
```diff
@@ -357,4 +368,75 @@ describe('util/extension-runners/chromium', async () => {
...
+      await runnerInstance.reloadAllExtensions();
+    });
+
+    it('resolve when all client disconnect', async () => {
+      await connectClient();
+      await new Promise((resolve) => {
+        wsClient.on('close', () => {
+          resolve(runnerInstance.reloadAllExtensions());
+        });
+        wsClient.close();
```
Comment (Rob--W) [inline tests/unit/test-extension-runners/test.chromium.js]: Need `wsClient = null;` as well.

File: src/extension-runners/chromium.js [hunk 16]
```diff
@@ -151,12 +151,41 @@ export class ChromiumExtensionRunner {
...
+  async wssBroadcast(data: Object) {
+    return new Promise((resolve) => {
+      const clients = this.wss ? new Set(this.wss.clients) : new Set();
+
+      const webExtReloadComplete = async (message) => {
+        const msg = JSON.parse(message);
+
+        if (msg.type === 'webExtReloadExtensionComplete') {
+          for (const client of clients) {
+            client.off('message', webExtReloadComplete);
```
Comment (Rob--W) [inline src/extension-runners/chromium.js]: I noticed that the tests fail on Node 8. That is because EventEmitter's `off` method was only introduced in Node 10.
We're going to drop support for Node 8 soon, because Node 8 is EOL in 2 months from now (https://github.com/nodejs/Release#release-schedule ).

If you want to land your patch *before* we drop Node 8 support, then you need to change `.off` to `removeListener` (3x)

File: src/extension-runners/chromium.js [hunk 17]
```diff
@@ -151,12 +151,41 @@ export class ChromiumExtensionRunner {
...
+          }
+          resolve();
+        }
+      };
+
+      for (const client of clients) {
+        if (client.readyState === WebSocket.OPEN) {
+          client.on('message', webExtReloadComplete);
+          const cleanWebExtReloadComplete = () => {
```
Comment (Rob--W) [inline src/extension-runners/chromium.js]: Move this to before `if (msg.type === 'webExtReloadExtensionComplete') {` and use a function expression instead of an arrow funtion. Then you can use `let client = this;`.

By doing so, you will be able to remove the `'close'` listener inside the `if (msg.type === 'webExtReloadExtensionComplete') {` handler as well (which is the reason why I wrote this comment in the first place).

File: src/extension-runners/chromium.js (hunk 16 above)
Comment (Rob--W) [reply src/extension-runners/chromium.js]: We have dropped for Node 8:  https://github.com/mozilla/web-ext/commit/884106c65f5e89a9e3c36b2dbb0609a1af27501d
... so you can use `.off` again.

File: src/extension-runners/chromium.js [hunk 18]
```diff
@@ -151,12 +151,42 @@ export class ChromiumExtensionRunner {
...
+        clients.delete(client);
       }
-    }
+
+      const webExtReloadComplete = async (message) => {
+        const msg = JSON.parse(message.data);
+
+        if (msg.type === 'webExtReloadExtensionComplete') {
+          for (const client of clients) {
+            client.removeEventListener('message', webExtReloadComplete);
```
Comment (Rob--W) [inline src/extension-runners/chromium.js]: This should be replaced with `cleanWebExtReloadComplete.call(client);`

File: src/extension-runners/chromium.js [hunk 19]
```diff
@@ -151,12 +151,42 @@ export class ChromiumExtensionRunner {
...
-    for (const client of this.wss.clients) {
-      if (client.readyState === WebSocket.OPEN) {
-        client.send(JSON.stringify(data));
+  async wssBroadcast(data: Object) {
+    return new Promise((resolve) => {
+      const clients = this.wss ? new Set(this.wss.clients) : new Set();
+
+      function cleanWebExtReloadComplete() {
+        const client = this;
+        client.removeEventListener('message', webExtReloadComplete);
```
Comment (Rob--W) [inline src/extension-runners/chromium.js]: You should also remove the `close` listener.

**Comment by ccarruitero** [comment]
@Rob--W Thanks a lot for all your comments. I just updated the PR.

File: src/extension-runners/chromium.js (hunk 16 above)
Comment (ccarruitero) [reply src/extension-runners/chromium.js]: I'm getting some timeout errors when change to on/off. I think we could keep add/remove listener keywords.
